name: Create Image

on:
  workflow_dispatch:   # ðŸ‘ˆ This enables manual "Run workflow"
  pull_request:
    types: [ closed ]
    paths-ignore:
      - '.github/README.md'
      - 'bucketActions/**'
      - 'terraform/**'
      - '.gitignore'
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  STAGING_INSTANCE_ID: 'i-057ba06636c67355f'
  AWS_REGION: 'us-east-1'

jobs:
  create_image:
    # Run only if PR was merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install boto3
        run: pip install boto3

      - name: Create AMI from instance
        working-directory: .github/ci_scripts
        run: python create_ami.py

      - name: Stop Staging Server
        if: always()
        working-directory: .github/ci_scripts
        run: python stop_staging_server.py

  stop_staging_server:
    # Run only if PR closed WITHOUT merge
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install boto3
        run: pip install boto3

      - name: Stop Staging Server
        working-directory: .github/ci_scripts
        run: python stop_staging_server.py
